name: avatar_maker
description: A light-weight and highly customizable SVG avatar library for
  Flutter apps. Provides a Customizer Widget, CircleAvatar and other utility
  functions that are ready-to-use.
version: 1.5.0
homepage: https://github.com/RoadTripMoustache/avatar_maker

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  intl: ^0.20.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
dev_dependencies:
  analyzer: ^8.1.1
  build_runner: ^2.10.1
  flutter_gen: ^5.12.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.5.1

flutter:
  assets:
    - assets/icons/
